### ISSUE TITLE
Searching / Playing songs is too slow

### ISSUE THREAD

**Issue by SuhasDissa** [you-apps/MellowMusic#1]
I wanted to let you know that if you're experiencing slow search suggestions or audio playback buffering, it's likely because backend servers are busy. To improve your experience, I recommend changing the server in your app settings.

To do this, open the app and go to `Settings > Network Settings`. Then, select a different server from the list.

I hope this helps!

Thanks,

**Comment by Bnyro** [comment]
We should either allow using a custom instance or fetch the list of public instances instead of showing only the few hardcoded ones.

**Comment by SuhasDissa** [comment]
That's a good idea. We might need to do some refactoring to get it to work.
