### ISSUE TITLE
automatic backup function 

### ISSUE THREAD

**Issue by siggi1984** [you-apps/MellowMusic#15]
An automatic backup feature like Blackhole would be very useful when you change your phone or tablet.

**Comment by Bnyro** [comment]
That's kinda unnecessary, just create a backup manually before switching the device.

**Comment by siggi1984** [comment]
But what if the cell phone is lost, stolen or broken and I can no longer access the data. In such a case, an automatic backup would be e.g. Being automatically saved in my cloud makes a lot of sense, right?

**Comment by Bnyro** [comment]
Feel free to create a PR for it if you feel better then.

**Comment by siggi1984** [comment]
It's okay, stay cool.
